<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  FuturePay\SDK\CreditDecisioning
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FuturePay\SDK\CreditDecisioning\Api;

use \FuturePay\SDK\CreditDecisioning\ApiClient;
use \FuturePay\SDK\CreditDecisioning\ApiException;
use \FuturePay\SDK\CreditDecisioning\Configuration;
use \FuturePay\SDK\CreditDecisioning\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  FuturePay\SDK\CreditDecisioning
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApi
{
    /**
     * API Client
     *
     * @var \FuturePay\SDK\CreditDecisioning\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \FuturePay\SDK\CreditDecisioning\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\FuturePay\SDK\CreditDecisioning\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \FuturePay\SDK\CreditDecisioning\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \FuturePay\SDK\CreditDecisioning\ApiClient $apiClient set the API client
     *
     * @return DefaultApi
     */
    public function setApiClient(\FuturePay\SDK\CreditDecisioning\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation decision
     *
     * Submit some information to perform a decision on
     *
     * @param \SplFileObject $creditFile TUNA Customer Credit File (required)
     * @param string $firstName  (required)
     * @param string $lastName  (required)
     * @param string $city  (required)
     * @param string $region  (required)
     * @param string $zip  (required)
     * @param string $dob  (required)
     * @param string $ssn  (required)
     * @param string $address  (required)
     * @throws \FuturePay\SDK\CreditDecisioning\ApiException on non-2xx response
     * @return \FuturePay\SDK\CreditDecisioning\Model\InlineResponse200
     */
    public function decision($creditFile, $firstName, $lastName, $city, $region, $zip, $dob, $ssn, $address)
    {
        list($response) = $this->decisionWithHttpInfo($creditFile, $firstName, $lastName, $city, $region, $zip, $dob, $ssn, $address);
        return $response;
    }

    /**
     * Operation decisionWithHttpInfo
     *
     * Submit some information to perform a decision on
     *
     * @param \SplFileObject $creditFile TUNA Customer Credit File (required)
     * @param string $firstName  (required)
     * @param string $lastName  (required)
     * @param string $city  (required)
     * @param string $region  (required)
     * @param string $zip  (required)
     * @param string $dob  (required)
     * @param string $ssn  (required)
     * @param string $address  (required)
     * @throws \FuturePay\SDK\CreditDecisioning\ApiException on non-2xx response
     * @return array of \FuturePay\SDK\CreditDecisioning\Model\InlineResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function decisionWithHttpInfo($creditFile, $firstName, $lastName, $city, $region, $zip, $dob, $ssn, $address)
    {
        // verify the required parameter 'creditFile' is set
        if ($creditFile === null) {
            throw new \InvalidArgumentException('Missing the required parameter $creditFile when calling decision');
        }
        // verify the required parameter 'firstName' is set
        if ($firstName === null) {
            throw new \InvalidArgumentException('Missing the required parameter $firstName when calling decision');
        }
        // verify the required parameter 'lastName' is set
        if ($lastName === null) {
            throw new \InvalidArgumentException('Missing the required parameter $lastName when calling decision');
        }
        // verify the required parameter 'city' is set
        if ($city === null) {
            throw new \InvalidArgumentException('Missing the required parameter $city when calling decision');
        }
        // verify the required parameter 'region' is set
        if ($region === null) {
            throw new \InvalidArgumentException('Missing the required parameter $region when calling decision');
        }
        // verify the required parameter 'zip' is set
        if ($zip === null) {
            throw new \InvalidArgumentException('Missing the required parameter $zip when calling decision');
        }
        // verify the required parameter 'dob' is set
        if ($dob === null) {
            throw new \InvalidArgumentException('Missing the required parameter $dob when calling decision');
        }
        // verify the required parameter 'ssn' is set
        if ($ssn === null) {
            throw new \InvalidArgumentException('Missing the required parameter $ssn when calling decision');
        }
        // verify the required parameter 'address' is set
        if ($address === null) {
            throw new \InvalidArgumentException('Missing the required parameter $address when calling decision');
        }
        // parse inputs
        $resourcePath = "/decision";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['multipart/form-data']);

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($creditFile !== null) {
            // PHP 5.5 introduced a CurlFile object that deprecates the old @filename syntax
            // See: https://wiki.php.net/rfc/curl-file-upload
            if (function_exists('curl_file_create')) {
                $formParams['credit_file'] = curl_file_create($this->apiClient->getSerializer()->toFormValue($creditFile));
            } else {
                $formParams['credit_file'] = '@' . $this->apiClient->getSerializer()->toFormValue($creditFile);
            }
        }
        // form params
        if ($firstName !== null) {
            $formParams['first_name'] = $this->apiClient->getSerializer()->toFormValue($firstName);
        }
        // form params
        if ($lastName !== null) {
            $formParams['last_name'] = $this->apiClient->getSerializer()->toFormValue($lastName);
        }
        // form params
        if ($city !== null) {
            $formParams['city'] = $this->apiClient->getSerializer()->toFormValue($city);
        }
        // form params
        if ($region !== null) {
            $formParams['region'] = $this->apiClient->getSerializer()->toFormValue($region);
        }
        // form params
        if ($zip !== null) {
            $formParams['zip'] = $this->apiClient->getSerializer()->toFormValue($zip);
        }
        // form params
        if ($dob !== null) {
            $formParams['dob'] = $this->apiClient->getSerializer()->toFormValue($dob);
        }
        // form params
        if ($ssn !== null) {
            $formParams['ssn'] = $this->apiClient->getSerializer()->toFormValue($ssn);
        }
        // form params
        if ($address !== null) {
            $formParams['address'] = $this->apiClient->getSerializer()->toFormValue($address);
        }
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\FuturePay\SDK\CreditDecisioning\Model\InlineResponse200',
                '/decision'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\FuturePay\SDK\CreditDecisioning\Model\InlineResponse200', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\FuturePay\SDK\CreditDecisioning\Model\InlineResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
