<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * InlineResponse200 Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200 implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'supplied_information' => '\Swagger\Client\Model\InlineResponse200SuppliedInformation',
        'credit_information' => '\Swagger\Client\Model\InlineResponse200CreditInformation',
        'decision' => '\Swagger\Client\Model\InlineResponse200Decision'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'supplied_information' => 'supplied_information',
        'credit_information' => 'credit_information',
        'decision' => 'decision'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'supplied_information' => 'setSuppliedInformation',
        'credit_information' => 'setCreditInformation',
        'decision' => 'setDecision'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'supplied_information' => 'getSuppliedInformation',
        'credit_information' => 'getCreditInformation',
        'decision' => 'getDecision'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['supplied_information'] = isset($data['supplied_information']) ? $data['supplied_information'] : null;
        $this->container['credit_information'] = isset($data['credit_information']) ? $data['credit_information'] : null;
        $this->container['decision'] = isset($data['decision']) ? $data['decision'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets supplied_information
     * @return \Swagger\Client\Model\InlineResponse200SuppliedInformation
     */
    public function getSuppliedInformation()
    {
        return $this->container['supplied_information'];
    }

    /**
     * Sets supplied_information
     * @param \Swagger\Client\Model\InlineResponse200SuppliedInformation $supplied_information
     * @return $this
     */
    public function setSuppliedInformation($supplied_information)
    {
        $this->container['supplied_information'] = $supplied_information;

        return $this;
    }

    /**
     * Gets credit_information
     * @return \Swagger\Client\Model\InlineResponse200CreditInformation
     */
    public function getCreditInformation()
    {
        return $this->container['credit_information'];
    }

    /**
     * Sets credit_information
     * @param \Swagger\Client\Model\InlineResponse200CreditInformation $credit_information
     * @return $this
     */
    public function setCreditInformation($credit_information)
    {
        $this->container['credit_information'] = $credit_information;

        return $this;
    }

    /**
     * Gets decision
     * @return \Swagger\Client\Model\InlineResponse200Decision
     */
    public function getDecision()
    {
        return $this->container['decision'];
    }

    /**
     * Sets decision
     * @param \Swagger\Client\Model\InlineResponse200Decision $decision
     * @return $this
     */
    public function setDecision($decision)
    {
        $this->container['decision'] = $decision;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


