<?php
/**
 * InputCategoryCreditRule
 *
 * PHP version 5
 *
 * @category Class
 * @package  FuturePay\SDK\CreditDecisioning
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FuturePay\SDK\CreditDecisioning\Model;

use \ArrayAccess;

/**
 * InputCategoryCreditRule Class Doc Comment
 *
 * @category    Class
 * @package     FuturePay\SDK\CreditDecisioning
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InputCategoryCreditRule implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'input_category_credit_rule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'minimumFicoScore' => 'int',
        'creditLine' => 'int',
        'minimumMonthlyIncome' => 'int',
        'dti' => 'float'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'minimumFicoScore' => 'minimum_fico_score',
        'creditLine' => 'credit_line',
        'minimumMonthlyIncome' => 'minimum_monthly_income',
        'dti' => 'dti'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'minimumFicoScore' => 'setMinimumFicoScore',
        'creditLine' => 'setCreditLine',
        'minimumMonthlyIncome' => 'setMinimumMonthlyIncome',
        'dti' => 'setDti'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'minimumFicoScore' => 'getMinimumFicoScore',
        'creditLine' => 'getCreditLine',
        'minimumMonthlyIncome' => 'getMinimumMonthlyIncome',
        'dti' => 'getDti'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['minimumFicoScore'] = isset($data['minimumFicoScore']) ? $data['minimumFicoScore'] : null;
        $this->container['creditLine'] = isset($data['creditLine']) ? $data['creditLine'] : null;
        $this->container['minimumMonthlyIncome'] = isset($data['minimumMonthlyIncome']) ? $data['minimumMonthlyIncome'] : null;
        $this->container['dti'] = isset($data['dti']) ? $data['dti'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['minimumFicoScore'] === null) {
            $invalid_properties[] = "'minimumFicoScore' can't be null";
        }
        if ($this->container['creditLine'] === null) {
            $invalid_properties[] = "'creditLine' can't be null";
        }
        if ($this->container['minimumMonthlyIncome'] === null) {
            $invalid_properties[] = "'minimumMonthlyIncome' can't be null";
        }
        if ($this->container['dti'] === null) {
            $invalid_properties[] = "'dti' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['minimumFicoScore'] === null) {
            return false;
        }
        if ($this->container['creditLine'] === null) {
            return false;
        }
        if ($this->container['minimumMonthlyIncome'] === null) {
            return false;
        }
        if ($this->container['dti'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets minimumFicoScore
     * @return int
     */
    public function getMinimumFicoScore()
    {
        return $this->container['minimumFicoScore'];
    }

    /**
     * Sets minimumFicoScore
     * @param int $minimumFicoScore
     * @return $this
     */
    public function setMinimumFicoScore($minimumFicoScore)
    {
        $this->container['minimumFicoScore'] = $minimumFicoScore;

        return $this;
    }

    /**
     * Gets creditLine
     * @return int
     */
    public function getCreditLine()
    {
        return $this->container['creditLine'];
    }

    /**
     * Sets creditLine
     * @param int $creditLine
     * @return $this
     */
    public function setCreditLine($creditLine)
    {
        $this->container['creditLine'] = $creditLine;

        return $this;
    }

    /**
     * Gets minimumMonthlyIncome
     * @return int
     */
    public function getMinimumMonthlyIncome()
    {
        return $this->container['minimumMonthlyIncome'];
    }

    /**
     * Sets minimumMonthlyIncome
     * @param int $minimumMonthlyIncome
     * @return $this
     */
    public function setMinimumMonthlyIncome($minimumMonthlyIncome)
    {
        $this->container['minimumMonthlyIncome'] = $minimumMonthlyIncome;

        return $this;
    }

    /**
     * Gets dti
     * @return float
     */
    public function getDti()
    {
        return $this->container['dti'];
    }

    /**
     * Sets dti
     * @param float $dti
     * @return $this
     */
    public function setDti($dti)
    {
        $this->container['dti'] = $dti;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\FuturePay\SDK\CreditDecisioning\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\FuturePay\SDK\CreditDecisioning\ObjectSerializer::sanitizeForSerialization($this));
    }
}


