<?php
/**
 * CreditSummaryTotalHistoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FuturePay\SDK\CreditDecisioning
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FuturePay\SDK\CreditDecisioning;

/**
 * CreditSummaryTotalHistoryTest Class Doc Comment
 *
 * @category    Class */
// * @description CreditSummaryTotalHistory
/**
 * @package     FuturePay\SDK\CreditDecisioning
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditSummaryTotalHistoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreditSummaryTotalHistory"
     */
    public function testCreditSummaryTotalHistory()
    {

    }

    /**
     * Test attribute "publicRecordCount"
     */
    public function testPropertyPublicRecordCount()
    {

    }

    /**
     * Test attribute "collectionCount"
     */
    public function testPropertyCollectionCount()
    {

    }

    /**
     * Test attribute "totalTradeCount"
     */
    public function testPropertyTotalTradeCount()
    {

    }

    /**
     * Test attribute "negativeTradeCount"
     */
    public function testPropertyNegativeTradeCount()
    {

    }

    /**
     * Test attribute "historicalNegativeTradeCount"
     */
    public function testPropertyHistoricalNegativeTradeCount()
    {

    }

    /**
     * Test attribute "historicalNegativeOccurrencesCount"
     */
    public function testPropertyHistoricalNegativeOccurrencesCount()
    {

    }

    /**
     * Test attribute "revolvingTradeCount"
     */
    public function testPropertyRevolvingTradeCount()
    {

    }

    /**
     * Test attribute "installmentTradeCount"
     */
    public function testPropertyInstallmentTradeCount()
    {

    }

    /**
     * Test attribute "mortgageTradeCount"
     */
    public function testPropertyMortgageTradeCount()
    {

    }

    /**
     * Test attribute "openTradeCount"
     */
    public function testPropertyOpenTradeCount()
    {

    }

    /**
     * Test attribute "unspecifiedTradeCount"
     */
    public function testPropertyUnspecifiedTradeCount()
    {

    }

    /**
     * Test attribute "totalInquiryCount"
     */
    public function testPropertyTotalInquiryCount()
    {

    }

}
