<?php
/**
 * DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FuturePay\SDK\CreditDecisioning
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FuturePay\SDK\CreditDecisioning;

/**
 * DataTest Class Doc Comment
 *
 * @category    Class */
// * @description Data
/**
 * @package     FuturePay\SDK\CreditDecisioning
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Data"
     */
    public function testData()
    {

    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {

    }

    /**
     * Test attribute "s3UrlCreditFile"
     */
    public function testPropertyS3UrlCreditFile()
    {

    }

    /**
     * Test attribute "categoryCreditRule"
     */
    public function testPropertyCategoryCreditRule()
    {

    }

}
