<?php
/**
 * InlineResponse200SuppliedInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200SuppliedInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse200SuppliedInformation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200SuppliedInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponse200SuppliedInformation"
     */
    public function testInlineResponse200SuppliedInformation()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {

    }

    /**
     * Test attribute "ssn"
     */
    public function testPropertySsn()
    {

    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {

    }

}
