<?php
/**
 * InlineResponse200CreditInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Credit Decision
 *
 * This is a microservice used to make a credit decision for a user based on input
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@futurepay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200CreditInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse200CreditInformation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200CreditInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponse200CreditInformation"
     */
    public function testInlineResponse200CreditInformation()
    {

    }

    /**
     * Test attribute "ofac_message"
     */
    public function testPropertyOfacMessage()
    {

    }

    /**
     * Test attribute "fico_score"
     */
    public function testPropertyFicoScore()
    {

    }

    /**
     * Test attribute "vantage_score"
     */
    public function testPropertyVantageScore()
    {

    }

    /**
     * Test attribute "debit_income_estimator_score"
     */
    public function testPropertyDebitIncomeEstimatorScore()
    {

    }

    /**
     * Test attribute "ssn"
     */
    public function testPropertySsn()
    {

    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {

    }

    /**
     * Test attribute "fraud_alert"
     */
    public function testPropertyFraudAlert()
    {

    }

    /**
     * Test attribute "deceased_date"
     */
    public function testPropertyDeceasedDate()
    {

    }

}
